import type { Plugin } from "@opencode-ai/plugin"

/**
 * smart-approval
 * --------------
 * Goal: the user should almost never be interrupted by a permission prompt,
 * while genuinely dangerous operations are still blocked.
 *
 * Layer 1 (static): deny rules in opencode.jsonc (secrets, .git, sudo, ...).
 * Layer 2 (this plugin): the `permission.ask` hook converts adaptive "ask"
 * decisions into an automatic allow/deny using the policy below.
 *
 * Safety invariant: this hook NEVER turns a configured `deny` into an `allow`.
 * If the incoming status is already a hard allow/deny it is left untouched;
 * only "ask" (or an unset status, when opencode uses the hook as the decision
 * point) is resolved by policy.
 */

type Rule = { re: RegExp; why: string }

/** Bash commands that must never run without the human explicitly asking. */
const DANGEROUS_BASH: Rule[] = [
  { re: /\bsudo\b/, why: "privilege escalation" },
  { re: /\bsu\s+(-|root)/, why: "privilege escalation" },
  { re: /\brm\s+-[a-z]*r[a-z]*f[a-z]*\s+\/(\s|$)/, why: "recursive delete of filesystem root" },
  { re: /\brm\s+-[a-z]*r[a-z]*f[a-z]*\s+\/\*/, why: "recursive delete of filesystem root" },
  { re: /\brm\s+-[a-z]*r[a-z]*f[a-z]*\s+~(\/|\s|$)/, why: "recursive delete of home directory" },
  { re: /\bmkfs(\.|\s|$)/, why: "filesystem format" },
  { re: /\bdd\b[^\n]*\bof=\/dev\//, why: "raw write to block device" },
  { re: /\b(shutdown|reboot|halt|poweroff)\b/, why: "system power control" },
  { re: /:\s*\(\s*\)\s*\{.*\};?\s*:/, why: "fork bomb" },
  { re: /\bchmod\s+-R\s+777\s+\/(\s|$)/, why: "world-writable filesystem root" },
  { re: /\bgit\s+push\b[^\n]*(--force\b|(^|\s)-f(\s|$))/, why: "force push overwrites remote history" },
  { re: /\b(curl|wget)\b[^\n|]*\|\s*(sudo\s+)?(ba|z|d)?sh\b/, why: "piping remote content into a shell" },
  { re: /\bhistory\s+-c\b/, why: "destroys shell audit trail" },
  { re: />\s*\/dev\/sd[a-z]/, why: "raw write to disk device" },
]

/** File paths that must not be edited automatically (credentials / noise). */
const PROTECTED_EDIT: Rule[] = [
  { re: /(^|\/)\.env(\.[^/]*)?$/, why: "environment secrets" },
  { re: /\.(key|secret|pem|p12|pfx|jks)$/i, why: "private key / certificate material" },
  { re: /(^|\/)id_(rsa|ed25519|ecdsa)(\.pub)?$/, why: "SSH private key" },
  { re: /(^|\/)\.ssh\//, why: "SSH configuration" },
  { re: /(^|\/)\.aws\/credentials$/, why: "AWS credentials" },
  { re: /(^|\/)\.npmrc$/, why: "registry auth token" },
  { re: /(^|\/)\.pypirc$/, why: "registry auth token" },
  { re: /(^|\/)\.netrc$/, why: "stored credentials" },
  { re: /(^|\/)\.git\//, why: "git internals" },
  { re: /(^|\/)node_modules\//, why: "generated dependencies" },
  { re: /(^|\/)__pycache__\//, why: "generated bytecode" },
  { re: /\.pyc$/, why: "generated bytecode" },
]

/** Directories outside the workspace that stay blocked. */
const PROTECTED_DIRS: Rule[] = [
  { re: /(^|\/)\.ssh(\/|$)/, why: "SSH configuration" },
  { re: /(^|\/)\.aws(\/|$)/, why: "AWS credentials" },
  { re: /(^|\/)\.gnupg(\/|$)/, why: "GPG keyring" },
  { re: /(^|\/)\.config\/gcloud(\/|$)/, why: "GCP credentials" },
  { re: /(^|\/)\.kube(\/|$)/, why: "Kubernetes credentials" },
]

function asString(value: unknown): string {
  if (typeof value === "string") return value
  if (Array.isArray(value)) return value.map(asString).filter(Boolean).join(" ")
  if (value && typeof value === "object") {
    try {
      return JSON.stringify(value)
    } catch {
      return ""
    }
  }
  return ""
}

/** Match a rule against any individual pattern string (arrays are not joined). */
function match(rules: Rule[], parts: string[]): Rule | undefined {
  for (const rule of rules) {
    for (const part of parts) {
      if (part && rule.re.test(part)) return rule
    }
  }
  return undefined
}

/** Flatten the request into individual strings — never join across boundaries. */
function collectParts(input: any): string[] {
  const parts: string[] = []
  if (Array.isArray(input?.pattern)) {
    for (const p of input.pattern) {
      const s = asString(p)
      if (s) parts.push(s)
    }
  } else {
    const s = asString(input?.pattern)
    if (s) parts.push(s)
  }
  const title = asString(input?.title)
  if (title) parts.push(title)
  const meta = asString(input?.metadata)
  if (meta) parts.push(meta)
  return parts
}

function decide(type: string, parts: string[]): { status: "allow" | "deny"; why: string } {
  if (type === "bash") {
    const hit = match(DANGEROUS_BASH, parts)
    if (hit) return { status: "deny", why: hit.why }
    return { status: "allow", why: "routine shell command" }
  }

  if (type === "edit" || type === "write") {
    const hit = match(PROTECTED_EDIT, parts)
    if (hit) return { status: "deny", why: hit.why }
    return { status: "allow", why: "in-workspace file change" }
  }

  if (type === "external_directory") {
    const hit = match(PROTECTED_DIRS, parts)
    if (hit) return { status: "deny", why: hit.why }
    return { status: "allow", why: "non-sensitive external path" }
  }

  // read / glob / grep / list / task / webfetch / websearch / skill / ...
  return { status: "allow", why: "non-destructive tool" }
}

export default (async ({ client }) => {
  const log = async (level: string, message: string, extra?: unknown) => {
    try {
      await (client as any)?.app?.log?.({
        service: "smart-approval",
        level,
        message,
        extra,
      })
    } catch {
      // logging must never break a tool call
    }
  }

  return {
    "permission.ask": async (input: any, output: any) => {
      const current = output?.status

      // Respect hard decisions made by config — never weaken a deny.
      if (current === "allow" || current === "deny") return

      const type = asString(input?.type) || "unknown"
      const parts = collectParts(input)
      const { status, why } = decide(type, parts)

      output.status = status
      await log(status === "deny" ? "warn" : "info", `permission.${type}: ${status} (${why})`, {
        pattern: input?.pattern,
        title: input?.title,
      })
    },
  } as any
}) satisfies Plugin
